-- Create user_wishlist table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.user_wishlist (
    wishlist_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_wishlist_pkey PRIMARY KEY (wishlist_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT unique_account_inventory UNIQUE (account_id, inv_id)
);